[2024-08-07T20:33:45.513+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-07T20:33:45.661+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: space_exploration.satellite_response scheduled__2023-02-17T00:00:00+00:00 [queued]>
[2024-08-07T20:33:45.701+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: space_exploration.satellite_response scheduled__2023-02-17T00:00:00+00:00 [queued]>
[2024-08-07T20:33:45.711+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-07T20:33:46.241+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): satellite_response> on 2023-02-17 00:00:00+00:00
[2024-08-07T20:33:46.260+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=353) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-07T20:33:46.266+0000] {standard_task_runner.py:64} INFO - Started process 387 to run task
[2024-08-07T20:33:46.265+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'space_exploration', 'satellite_response', 'scheduled__2023-02-17T00:00:00+00:00', '--job-id', '96', '--raw', '--subdir', 'DAGS_FOLDER/***-space-exploration.py', '--cfg-path', '/tmp/tmp4g5i5ace']
[2024-08-07T20:33:46.271+0000] {standard_task_runner.py:91} INFO - Job 96: Subtask satellite_response
[2024-08-07T20:33:46.404+0000] {task_command.py:426} INFO - Running <TaskInstance: space_exploration.satellite_response scheduled__2023-02-17T00:00:00+00:00 [running]> on host 13935ade345d
[2024-08-07T20:33:46.731+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='space_exploration' AIRFLOW_CTX_TASK_ID='satellite_response' AIRFLOW_CTX_EXECUTION_DATE='2023-02-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-02-17T00:00:00+00:00'
[2024-08-07T20:33:46.735+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-07T20:33:46.799+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-08-07T20:33:46.802+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-07T20:33:46.849+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=space_exploration, task_id=satellite_response, run_id=scheduled__2023-02-17T00:00:00+00:00, execution_date=20230217T000000, start_date=20240807T203345, end_date=20240807T203346
[2024-08-07T20:33:46.941+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-07T20:33:47.043+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-07T20:33:47.052+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
