[2024-08-07T14:26:57.649+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-07T14:26:57.690+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airflow-space-exploration.Autorizacion_NASA manual__2024-08-07T14:20:08.695612+00:00 [queued]>
[2024-08-07T14:26:57.707+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airflow-space-exploration.Autorizacion_NASA manual__2024-08-07T14:20:08.695612+00:00 [queued]>
[2024-08-07T14:26:57.709+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 3
[2024-08-07T14:26:57.732+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): Autorizacion_NASA> on 2024-08-07 14:20:08.695612+00:00
[2024-08-07T14:26:57.742+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=579) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-07T14:26:57.744+0000] {standard_task_runner.py:64} INFO - Started process 588 to run task
[2024-08-07T14:26:57.745+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', '***-space-exploration', 'Autorizacion_NASA', 'manual__2024-08-07T14:20:08.695612+00:00', '--job-id', '99', '--raw', '--subdir', 'DAGS_FOLDER/***-space-exploration.py', '--cfg-path', '/tmp/tmpsq6uzz4q']
[2024-08-07T14:26:57.746+0000] {standard_task_runner.py:91} INFO - Job 99: Subtask Autorizacion_NASA
[2024-08-07T14:26:57.841+0000] {task_command.py:426} INFO - Running <TaskInstance: airflow-space-exploration.Autorizacion_NASA manual__2024-08-07T14:20:08.695612+00:00 [running]> on host 38873943cc86
[2024-08-07T14:26:58.004+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='***-space-exploration' AIRFLOW_CTX_TASK_ID='Autorizacion_NASA' AIRFLOW_CTX_EXECUTION_DATE='2024-08-07T14:20:08.695612+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-07T14:20:08.695612+00:00'
[2024-08-07T14:26:58.005+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-07T14:26:58.029+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-08-07T14:26:58.031+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "sleep 20 && echo 'OK' > /tmp/response_20240807.txt"]
[2024-08-07T14:26:58.044+0000] {subprocess.py:86} INFO - Output:
[2024-08-07T14:27:18.048+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-08-07T14:27:18.050+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-07T14:27:18.093+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=***-space-exploration, task_id=Autorizacion_NASA, run_id=manual__2024-08-07T14:20:08.695612+00:00, execution_date=20240807T142008, start_date=20240807T142657, end_date=20240807T142718
[2024-08-07T14:27:18.164+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-07T14:27:18.209+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-07T14:27:18.213+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
