[2024-08-07T14:24:11.191+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-07T14:24:11.243+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airflow-space-exploration.Ver_data manual__2024-08-07T14:20:08.695612+00:00 [queued]>
[2024-08-07T14:24:11.257+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airflow-space-exploration.Ver_data manual__2024-08-07T14:20:08.695612+00:00 [queued]>
[2024-08-07T14:24:11.258+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-07T14:24:11.290+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): Ver_data> on 2024-08-07 14:20:08.695612+00:00
[2024-08-07T14:24:11.299+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=428) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-07T14:24:11.300+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', '***-space-exploration', 'Ver_data', 'manual__2024-08-07T14:20:08.695612+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/***-space-exploration.py', '--cfg-path', '/tmp/tmptz5lcbcx']
[2024-08-07T14:24:11.301+0000] {standard_task_runner.py:64} INFO - Started process 436 to run task
[2024-08-07T14:24:11.303+0000] {standard_task_runner.py:91} INFO - Job 61: Subtask Ver_data
[2024-08-07T14:24:11.375+0000] {task_command.py:426} INFO - Running <TaskInstance: airflow-space-exploration.Ver_data manual__2024-08-07T14:20:08.695612+00:00 [running]> on host 38873943cc86
[2024-08-07T14:24:11.494+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='***-space-exploration' AIRFLOW_CTX_TASK_ID='Ver_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-07T14:20:08.695612+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-07T14:20:08.695612+00:00'
[2024-08-07T14:24:11.495+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-07T14:24:11.519+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-08-07T14:24:11.520+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "bash_command='ls /tmp && head /tmp/platzi_data.csv'"]
[2024-08-07T14:24:11.539+0000] {subprocess.py:86} INFO - Output:
[2024-08-07T14:24:11.541+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-08-07T14:24:11.543+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-07T14:24:11.592+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=***-space-exploration, task_id=Ver_data, run_id=manual__2024-08-07T14:20:08.695612+00:00, execution_date=20240807T142008, start_date=20240807T142411, end_date=20240807T142411
[2024-08-07T14:24:11.639+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-07T14:24:11.665+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-07T14:24:11.670+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
