[2024-08-07T15:02:25.738+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-07T15:02:25.772+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airflow-space-exploration.Respuesta_Satelite scheduled__2024-08-06T00:00:00+00:00 [queued]>
[2024-08-07T15:02:25.788+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airflow-space-exploration.Respuesta_Satelite scheduled__2024-08-06T00:00:00+00:00 [queued]>
[2024-08-07T15:02:25.790+0000] {taskinstance.py:2306} INFO - Starting attempt 6 of 6
[2024-08-07T15:02:25.817+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): Respuesta_Satelite> on 2024-08-06 00:00:00+00:00
[2024-08-07T15:02:25.825+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=333) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-07T15:02:25.827+0000] {standard_task_runner.py:64} INFO - Started process 340 to run task
[2024-08-07T15:02:25.827+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', '***-space-exploration', 'Respuesta_Satelite', 'scheduled__2024-08-06T00:00:00+00:00', '--job-id', '374', '--raw', '--subdir', 'DAGS_FOLDER/***-space-exploration.py', '--cfg-path', '/tmp/tmpb7d7vlze']
[2024-08-07T15:02:25.828+0000] {standard_task_runner.py:91} INFO - Job 374: Subtask Respuesta_Satelite
[2024-08-07T15:02:25.900+0000] {task_command.py:426} INFO - Running <TaskInstance: airflow-space-exploration.Respuesta_Satelite scheduled__2024-08-06T00:00:00+00:00 [running]> on host 38873943cc86
[2024-08-07T15:02:26.040+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='***-space-exploration' AIRFLOW_CTX_TASK_ID='Respuesta_Satelite' AIRFLOW_CTX_EXECUTION_DATE='2024-08-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-06T00:00:00+00:00'
[2024-08-07T15:02:26.044+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-07T15:02:27.129+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-08-07T15:02:27.131+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-07T15:02:27.149+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=***-space-exploration, task_id=Respuesta_Satelite, run_id=scheduled__2024-08-06T00:00:00+00:00, execution_date=20240806T000000, start_date=20240807T150225, end_date=20240807T150227
[2024-08-07T15:02:27.211+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-07T15:02:27.266+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-07T15:02:27.270+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
