[2024-08-07T20:33:08.148+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-07T20:33:08.237+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: space_exploration.nasa_confirmation_response scheduled__2023-02-10T00:00:00+00:00 [queued]>
[2024-08-07T20:33:08.257+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: space_exploration.nasa_confirmation_response scheduled__2023-02-10T00:00:00+00:00 [queued]>
[2024-08-07T20:33:08.259+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-07T20:33:08.828+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): nasa_confirmation_response> on 2023-02-10 00:00:00+00:00
[2024-08-07T20:33:08.843+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=84) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-07T20:33:08.850+0000] {standard_task_runner.py:64} INFO - Started process 101 to run task
[2024-08-07T20:33:08.853+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'space_exploration', 'nasa_confirmation_response', 'scheduled__2023-02-10T00:00:00+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/***-space-exploration.py', '--cfg-path', '/tmp/tmprev1wbnl']
[2024-08-07T20:33:08.861+0000] {standard_task_runner.py:91} INFO - Job 42: Subtask nasa_confirmation_response
[2024-08-07T20:33:08.991+0000] {task_command.py:426} INFO - Running <TaskInstance: space_exploration.nasa_confirmation_response scheduled__2023-02-10T00:00:00+00:00 [running]> on host 13935ade345d
[2024-08-07T20:33:09.226+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='space_exploration' AIRFLOW_CTX_TASK_ID='nasa_confirmation_response' AIRFLOW_CTX_EXECUTION_DATE='2023-02-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-02-10T00:00:00+00:00'
[2024-08-07T20:33:09.231+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-07T20:33:09.270+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-08-07T20:33:09.271+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'sleep 20 && echo "Confirmation from NASA, you can proceed." > /tmp/response_20230210.txt']
[2024-08-07T20:33:09.291+0000] {subprocess.py:86} INFO - Output:
[2024-08-07T20:33:29.297+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-08-07T20:33:29.299+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-07T20:33:29.347+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=space_exploration, task_id=nasa_confirmation_response, run_id=scheduled__2023-02-10T00:00:00+00:00, execution_date=20230210T000000, start_date=20240807T203308, end_date=20240807T203329
[2024-08-07T20:33:29.378+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-07T20:33:29.423+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-07T20:33:29.425+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
