[2024-08-07T14:58:41.298+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-07T14:58:41.332+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airflow-space-exploration.Autorizacion_NASA scheduled__2024-08-04T00:00:00+00:00 [queued]>
[2024-08-07T14:58:41.346+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airflow-space-exploration.Autorizacion_NASA scheduled__2024-08-04T00:00:00+00:00 [queued]>
[2024-08-07T14:58:41.347+0000] {taskinstance.py:2306} INFO - Starting attempt 11 of 11
[2024-08-07T14:58:41.370+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): Autorizacion_NASA> on 2024-08-04 00:00:00+00:00
[2024-08-07T14:58:41.381+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', '***-space-exploration', 'Autorizacion_NASA', 'scheduled__2024-08-04T00:00:00+00:00', '--job-id', '311', '--raw', '--subdir', 'DAGS_FOLDER/***-space-exploration.py', '--cfg-path', '/tmp/tmp0_niocdp']
[2024-08-07T14:58:41.379+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=65) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-07T14:58:41.384+0000] {standard_task_runner.py:91} INFO - Job 311: Subtask Autorizacion_NASA
[2024-08-07T14:58:41.384+0000] {standard_task_runner.py:64} INFO - Started process 72 to run task
[2024-08-07T14:58:41.460+0000] {task_command.py:426} INFO - Running <TaskInstance: airflow-space-exploration.Autorizacion_NASA scheduled__2024-08-04T00:00:00+00:00 [running]> on host 38873943cc86
[2024-08-07T14:58:41.575+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='***-space-exploration' AIRFLOW_CTX_TASK_ID='Autorizacion_NASA' AIRFLOW_CTX_EXECUTION_DATE='2024-08-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='11' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-04T00:00:00+00:00'
[2024-08-07T14:58:41.576+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-07T14:58:41.591+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-08-07T14:58:41.592+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "sleep 20 && echo 'ConfirmaciÃ³n de la NASA, pueden proceder' > /tmp/response_20240804.txt"]
[2024-08-07T14:58:41.604+0000] {subprocess.py:86} INFO - Output:
[2024-08-07T14:59:01.607+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-08-07T14:59:01.609+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-07T14:59:01.649+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=***-space-exploration, task_id=Autorizacion_NASA, run_id=scheduled__2024-08-04T00:00:00+00:00, execution_date=20240804T000000, start_date=20240807T145841, end_date=20240807T145901
[2024-08-07T14:59:01.693+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-07T14:59:01.732+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-07T14:59:01.737+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
